### ISSUE TITLE
Interrupthandle

### ISSUE THREAD

**Issue by bookghf** [petoknm/DHT22#3]
I’m just beginner on stm32 and dht22 i have a question about function dht22_interruptdandle . How this function work and where does it was called? Thank you

**Comment by petoknm** [comment]
If you are referring to `void DHT22_InterruptHandler(DHT22_HandleTypeDef* handle);` then it is to be called in an interrupt handler for the timer you chose for the timing (the one set in the `DHT22_HandleTypeDef`). The example doesn't have it because I probably forgot to include it there. It should be in the `example_it.c` file within the `TIM3_IRQHandler` function after `HAL_TIM_IRQHandler(&dht.timHandle);`

**Comment by bookghf** [comment]
oh its work but humidity was always max value ,I think its was sensor
problem . Thank you

2017-12-18 2:03 GMT+07:00 Peter Majchrak <notifications@github.com>:

**Comment by petoknm** [comment]
You can try it for example with an arduino to see if it gives the same readings. There is currently an issue that someone reported differences between arduino and stm32 readings and I will be investigating that in January most likely.
